# Generated by Django 4.2.3 on 2023-07-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='photos/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
